/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.forms;

/**
 *
 * @author antrn
 */
public class ChuyenBayControlForm extends javax.swing.JPanel {

    /**
     * Creates new form ChuyenBayControlForm
     */
    public ChuyenBayControlForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        myCombobox1 = new GUI.panel.swing.MyCombobox();
        myCombobox2 = new GUI.panel.swing.MyCombobox();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        myButton2 = new GUI.panel.swing.MyButton();
        myButton1 = new GUI.panel.swing.MyButton();
        myButton3 = new GUI.panel.swing.MyButton();
        myButton4 = new GUI.panel.swing.MyButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1065, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Danh Sách Chuyến Bay");
        jLabel1.setPreferredSize(new java.awt.Dimension(151, 31));
        jLabel1.setRequestFocusEnabled(false);

        myCombobox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sắp xếp theo: Mã chuyến bay", "Sắp xếp theo: Giá thường", "Sắp xếp: Theo giá Vip" }));
        myCombobox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        myCombobox1.setPreferredSize(new java.awt.Dimension(250, 31));
        myCombobox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myCombobox1ActionPerformed(evt);
            }
        });

        myCombobox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tăng dần", "Giảm dần" }));
        myCombobox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        myCombobox2.setPreferredSize(new java.awt.Dimension(119, 31));

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(274, 31));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setPreferredSize(new java.awt.Dimension(64, 31));
        jPanel1.add(jTextField1);

        myButton2.setBackground(new java.awt.Color(0, 204, 255));
        myButton2.setBorder(null);
        myButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/search.png"))); // NOI18N
        myButton2.setBorderColor(new java.awt.Color(0, 204, 255));
        myButton2.setColorClick(new java.awt.Color(0, 153, 255));
        myButton2.setColorOver(new java.awt.Color(0, 204, 255));
        myButton2.setOpaque(true);
        myButton2.setPreferredSize(new java.awt.Dimension(31, 31));
        jPanel1.add(myButton2);

        myButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/Xoa.png"))); // NOI18N
        myButton1.setText("Xóa");
        myButton1.setBorderColor(new java.awt.Color(204, 204, 204));
        myButton1.setColorClick(new java.awt.Color(0, 204, 255));
        myButton1.setColorOver(new java.awt.Color(0, 204, 255));
        myButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        myButton1.setPreferredSize(new java.awt.Dimension(100, 31));

        myButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/plus.png"))); // NOI18N
        myButton3.setText("Thêm");
        myButton3.setBorderColor(new java.awt.Color(204, 204, 204));
        myButton3.setColorClick(new java.awt.Color(0, 204, 255));
        myButton3.setColorOver(new java.awt.Color(0, 204, 255));
        myButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        myButton3.setPreferredSize(new java.awt.Dimension(100, 31));

        myButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/edit.png"))); // NOI18N
        myButton4.setText("Sửa");
        myButton4.setBorderColor(new java.awt.Color(204, 204, 204));
        myButton4.setColorClick(new java.awt.Color(0, 204, 255));
        myButton4.setColorOver(new java.awt.Color(0, 204, 255));
        myButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        myButton4.setPreferredSize(new java.awt.Dimension(100, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(myCombobox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(myCombobox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(myButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(myCombobox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(myCombobox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(myButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myCombobox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myCombobox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myCombobox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private GUI.panel.swing.MyButton myButton1;
    private GUI.panel.swing.MyButton myButton2;
    private GUI.panel.swing.MyButton myButton3;
    private GUI.panel.swing.MyButton myButton4;
    private GUI.panel.swing.MyCombobox myCombobox1;
    private GUI.panel.swing.MyCombobox myCombobox2;
    // End of variables declaration//GEN-END:variables
}
