/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.forms;

/**
 *
 * @author Lenovo
 */
public class FormGroup extends javax.swing.JPanel {

    /**
     * Creates new form FormGroup
     */
    public FormGroup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeForm1 = new GUI.forms.HomeForm();
        homeForm21 = new GUI.forms.HomeForm2();
        homeForm2 = new GUI.forms.HomeForm();

        add(homeForm21);
        add(homeForm2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.forms.HomeForm homeForm1;
    private GUI.forms.HomeForm homeForm2;
    private GUI.forms.HomeForm2 homeForm21;
    // End of variables declaration//GEN-END:variables
}
