/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.forms;

/**
 *
 * @author Lenovo
 */
public class ThongTinKhachHangForm extends javax.swing.JPanel {

    /**
     * Creates new form ThonTinKhachHangForm
     */
    public ThongTinKhachHangForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ctMaNhanVien = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        ctHoNhanVien = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        ctGioiTinhNhanVien = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ctTenTaiKhoan = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Thông tin khách hàng");
        jLabel1.setPreferredSize(new java.awt.Dimension(86, 30));
        jPanel1.add(jLabel1);

        add(jPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 12, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel4.setLayout(new java.awt.GridLayout(0, 1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(204, 30));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Tên: ");
        jLabel11.setMaximumSize(new java.awt.Dimension(120, 30));
        jLabel11.setMinimumSize(new java.awt.Dimension(120, 30));
        jLabel11.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel3.add(jLabel11);

        ctMaNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        ctMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ctMaNhanVien.setMaximumSize(new java.awt.Dimension(150, 30));
        ctMaNhanVien.setMinimumSize(new java.awt.Dimension(150, 30));
        ctMaNhanVien.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel3.add(ctMaNhanVien);

        jPanel4.add(jPanel3);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(204, 30));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Email");
        jLabel17.setMaximumSize(new java.awt.Dimension(120, 30));
        jLabel17.setMinimumSize(new java.awt.Dimension(120, 30));
        jLabel17.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel6.add(jLabel17);

        ctHoNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        ctHoNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ctHoNhanVien.setMaximumSize(new java.awt.Dimension(150, 30));
        ctHoNhanVien.setMinimumSize(new java.awt.Dimension(150, 30));
        ctHoNhanVien.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel6.add(ctHoNhanVien);

        jPanel4.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(204, 30));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Giới Tính: ");
        jLabel19.setMaximumSize(new java.awt.Dimension(120, 30));
        jLabel19.setMinimumSize(new java.awt.Dimension(120, 30));
        jLabel19.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel7.add(jLabel19);

        ctGioiTinhNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        ctGioiTinhNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ctGioiTinhNhanVien.setMaximumSize(new java.awt.Dimension(150, 30));
        ctGioiTinhNhanVien.setMinimumSize(new java.awt.Dimension(150, 30));
        ctGioiTinhNhanVien.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel7.add(ctGioiTinhNhanVien);

        jPanel4.add(jPanel7);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(204, 30));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mã Khách hàng: ");
        jLabel2.setMaximumSize(new java.awt.Dimension(120, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(120, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel2.add(jLabel2);

        ctTenTaiKhoan.setBackground(new java.awt.Color(255, 255, 255));
        ctTenTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ctTenTaiKhoan.setMaximumSize(new java.awt.Dimension(150, 30));
        ctTenTaiKhoan.setMinimumSize(new java.awt.Dimension(150, 30));
        ctTenTaiKhoan.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel2.add(ctTenTaiKhoan);

        jPanel4.add(jPanel2);

        add(jPanel4);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ctGioiTinhNhanVien;
    private javax.swing.JLabel ctHoNhanVien;
    private javax.swing.JLabel ctMaNhanVien;
    private javax.swing.JLabel ctTenTaiKhoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
