/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.panel.swing;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics2D;
import java.awt.Graphics;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;

/**
 *
 * @author antrn
 */
public class WelcomeLoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form WelcomeLoginPanel
     */
    public WelcomeLoginPanel() {
        initComponents();
        setOpaque(false);

    }
    @SuppressWarnings("unchecked")
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDrag = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        welcomeText = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(870, 800));

        panelDrag.setMinimumSize(new java.awt.Dimension(0, 0));
        panelDrag.setOpaque(false);
        panelDrag.setPreferredSize(new java.awt.Dimension(870, 800));

        welcome.setBackground(new java.awt.Color(255, 255, 255));
        welcome.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setText("Chào mừng");
        welcome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        welcomeText.setBackground(new java.awt.Color(255, 255, 255));
        welcomeText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        welcomeText.setForeground(new java.awt.Color(255, 255, 255));
        welcomeText.setText("các bạn đến với ứng dụng ");

        javax.swing.GroupLayout panelDragLayout = new javax.swing.GroupLayout(panelDrag);
        panelDrag.setLayout(panelDragLayout);
        panelDragLayout.setHorizontalGroup(
            panelDragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDragLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(panelDragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(welcomeText))
                .addContainerGap(412, Short.MAX_VALUE))
        );
        panelDragLayout.setVerticalGroup(
            panelDragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDragLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(welcomeText)
                .addContainerGap(448, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDrag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDrag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint gradient = new GradientPaint(0, 0, Color.decode("#1CB5E0"), getWidth(), 0, Color.decode("#000046"));
        g2d.setPaint(gradient);
        g2d.fillRect(0, 0, getWidth(), getHeight());
        super.paintComponent(g);
    }
    
    private int x, y;
    
    public void initMoving(JFrame frame){
        panelDrag.addMouseListener(new MouseAdapter(){
        @Override
        public void mousePressed(MouseEvent me){
            x = me.getX();
            y = me.getY();
        }
        });
        
        panelDrag.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent me) {
                frame.setLocation(me.getXOnScreen() - x, me.getYOnScreen() - y);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelDrag;
    private javax.swing.JLabel welcome;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
